export const INFO_LOAD = 'INFO_LOAD';
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS';
export const INFO_LOAD_FAIL = 'INFO_LOAD_FAIL';
export const WIDGET_LOAD = 'WIDGET_LOAD';
export const WIDGET_LOAD_SUCCESS = 'WIDGET_LOAD_SUCCESS';
export const WIDGET_LOAD_FAIL = 'WIDGET_LOAD_FAIL';
export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const ROOM_CREATE = 'ROOM_CREATE';
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS';
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL';

export const ROOM_LOAD = 'ROOM_LOAD';
export const ROOM_LOAD_SUCCESS = 'ROOM_LOAD_SUCCESS';
export const ROOM_LOAD_FAIL = 'ROOM_LOAD_FAIL';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_RECV = 'SOCKET_RECV';
export const SOCKET_SEND = 'SOCKET_SEND';
export const SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';

export const WORDS_REMOVE = 'WORDS_REMOVE';

